// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAebUhkfAyUlKyCYAAqXW6ajPKAJrb5XpI',
    appId: '1:490243548878:web:b41e52108f46267222129f',
    messagingSenderId: '490243548878',
    projectId: 'class-room-online',
    authDomain: 'class-room-online.firebaseapp.com',
    databaseURL: 'https://class-room-online-default-rtdb.firebaseio.com',
    storageBucket: 'class-room-online.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFECdowjF2GuUjkM-Q_KHq-fB8Ip91riM',
    appId: '1:490243548878:android:dc4008f8cda8913c22129f',
    messagingSenderId: '490243548878',
    projectId: 'class-room-online',
    databaseURL: 'https://class-room-online-default-rtdb.firebaseio.com',
    storageBucket: 'class-room-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyUkCEZBSLHzh3m3OC0z3OZLBkg6KdjQ',
    appId: '1:490243548878:ios:de59ccee2cb79c5522129f',
    messagingSenderId: '490243548878',
    projectId: 'class-room-online',
    databaseURL: 'https://class-room-online-default-rtdb.firebaseio.com',
    storageBucket: 'class-room-online.appspot.com',
    iosClientId: '490243548878-34de3rg777fs0shshud2l57hs3e9sr1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGyUkCEZBSLHzh3m3OC0z3OZLBkg6KdjQ',
    appId: '1:490243548878:ios:de59ccee2cb79c5522129f',
    messagingSenderId: '490243548878',
    projectId: 'class-room-online',
    databaseURL: 'https://class-room-online-default-rtdb.firebaseio.com',
    storageBucket: 'class-room-online.appspot.com',
    iosClientId: '490243548878-34de3rg777fs0shshud2l57hs3e9sr1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClass',
  );
}
